### ISSUE TITLE
Tooltip on hover for all buttons

### ISSUE THREAD

**Issue by ashwinvis** [coderefinery/obs-cr#8]
I see it is here:

https://github.com/coderefinery/obs-cr/blob/74d07865e28b31069cd236048ff3477b2d2c6340/web/index.html#L36-L45

We could add some helpful tooltips for all buttons. Some suggestions:

- Time: *Take a look at the clock*
- Notes: *Collaborative notes: something has come up*
- Question: *Your co-teacher has a question*
- Chat: *Zulip chat: something has come up*
- Slower: *Try to speak at a slower pace*
- Faster: *Try to speak at a faster pace*

Is that it? Corrections welcome, and I could do a PR

**Comment by rkdarst** [comment]
Thanks!  This is a good idea, it was really needed.  Your descriptions made it much easier.  I just made a push with basically these, with a few small updates.

PRs in the, future are always welcome, too.  Including continuing to improve things, and generally improve the instructions on the pages.

**Comment by ashwinvis** [comment]
Great! Closed via ec8bf62
